/** @type {import('tailwindcss').Config} */
// Design tokens ported 1:1 from the Stitch mockups' inline Tailwind config
// (see DESIGN.md). `primary` is unified to the documented brand accent #378ADD
// across all screens (mockups defined it inconsistently as #005ea4 / #378ADD).
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#378ADD",
        "accent-blue": "#378ADD",
        "on-primary": "#ffffff",
        "primary-container": "#1777c9",
        "on-primary-container": "#fdfcff",
        "primary-fixed": "#d2e4ff",
        "primary-fixed-dim": "#a1c9ff",
        "on-primary-fixed": "#001c38",
        "on-primary-fixed-variant": "#004880",
        "inverse-primary": "#a1c9ff",
        "surface-tint": "#0060a8",
        secondary: "#575e70",
        "on-secondary": "#ffffff",
        "secondary-container": "#d9dff5",
        "on-secondary-container": "#5c6274",
        "secondary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#c0c6db",
        "on-secondary-fixed": "#141b2b",
        "on-secondary-fixed-variant": "#404758",
        tertiary: "#874f00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a96400",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcbd",
        "tertiary-fixed-dim": "#ffb86f",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#693c00",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#ffffff",
        "on-background": "#191c1d",
        surface: "#f8f9fa",
        "surface-white": "#FFFFFF",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#414751",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        outline: "#717783",
        "outline-variant": "#c0c7d3",
        "border-subtle": "#E5E7EB",
        "text-muted": "#6B7280",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-page": "32px",
        "container-max": "1440px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "stack-xl": "48px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
      },
      fontSize: {
        display: ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "button-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
